version: '3.9'

services:
  
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER : postgres
      POSTGRES_PASSWORD : postgres
      POSTGRES_DB : taxidb
    ports:
      - "6001:5432"
    volumes:
      - ./ny_taxi_postgres_data:/var/lib/postgresql/data:rw
    container_name: database_postgres
    networks:
      - airflow_net
networks:
  airflow_net:
    external:
      name: airflow_default
   
   

